In [1]:
import datetime
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import pandas as pd
import time
from IPython.display import clear_output
import pprint
from matplotlib.pyplot import figure

In [19]:
team_data = pd.read_csv(r"C:\Users\Terrafirma\OwnLearning\PremierLeague\team_stats.csv")
player_data = pd.read_csv(r"C:\Users\Terrafirma\OwnLearning\PremierLeague\player_stats.csv")
team_data.drop("Unnamed: 0", axis=1, inplace=True)
player_data.drop("Unnamed: 0", axis=1, inplace=True)
player_data['ROI'] = round(player_data['ROI'], 3)
player_data.merge(team_data, left_on='Team', right_on='Team')

In [20]:
team_data

,Team,Team_SPI,Team_attack_score,Team_defence_score,Opponent_SPI,Opponent_attack_score,Opponent_defence_score,Predicted_points,GF_likelihood,GA_likelihood
0,Burnley,65.3,1.8,0.9,70.775,1.975,0.800,4.83,1.000,0.456
1,Crystal Palace,71.8,1.9,0.7,65.200,1.775,0.875,6.19,1.025,0.394
2,Brighton,76.8,1.9,0.5,76.450,2.100,0.650,5.23,1.250,0.238
3,Arsenal,77.9,2.1,0.6,68.600,1.800,0.775,6.70,1.325,0.333
4,Leicester,72.2,2.1,0.9,82.375,2.500,0.500,3.84,1.600,0.360
5,Chelsea,88.7,2.6,0.4,72.625,1.875,0.650,8.13,1.950,0.213
6,Liverpool,92.9,3.1,0.3,68.425,1.925,0.900,9.53,2.200,0.156
7,Man. United,78.2,2.2,0.7,68.200,1.775,0.775,7.37,1.425,0.394
8,Aston Villa,73.4,2.0,0.7,72.575,2.050,0.775,5.36,1.225,0.341
9,West Ham,77.6,2.1,0.6,66.325,1.800,0.850,7.10,1.250,0.333
10,Southampton,68.0,1.8,0.8,72.625,1.975,0.725,4.96,1.075,0.405
11,Watford,62.4,1.8,1.0,71.475,1.875,0.700,4.48,1.100,0.533
12,Leeds United,68.6,1.9,0.9,77.375,2.250,0.625,4.58,1.275,0.400
13,Everton,69.1,1.9,0.8,71.425,2.050,0.825,5.10,1.075,0.390
14,Wolves,71.2,1.7,0.6,76.450,2.100,0.625,4.44,1.075,0.286
15,Newcastle,59.5,1.7,1.1,83.575,2.550,0.500,2.37,1.200,0.431
16,Tottenham,73.4,2.0,0.7,76.225,2.225,0.675,4.94,1.325,0.315
17,Man. City,94.1,3.0,0.2,69.325,1.950,0.875,9.42,2.125,0.103
18,Norwich,57.0,1.5,1.0,74.875,2.050,0.700,2.94,0.800,0.488
19,Brentford,67.7,1.9,0.9,78.075,2.175,0.550,3.96,1.350,0.414

In [21]:
player_data

        Team      Player Position  Cost  Selected  Form   Pts     ROI
0    Arsenal    Ramsdale      GKP   5.1      16.7   4.0  70.0  13.725
1    Arsenal  Smith Rowe      MID   6.0      24.2   2.0  69.0  11.500
2    Arsenal     Gabriel      DEF   5.2       4.8   3.5  67.0  12.885
3    Arsenal        Saka      MID   6.2       8.8   3.0  58.0   9.355
4    Arsenal    Tomiyasu      DEF   4.7       5.3   3.3  54.0  11.489
..       ...         ...      ...   ...       ...   ...   ...     ...
575   Wolves       Jonny      DEF   4.5       0.0   0.0   0.0   0.000
576   Wolves    Mosquera      DEF   4.5       0.0   0.0   0.0   0.000
577   Wolves     Marques      DEF   4.0       0.2   0.0   0.0   0.000
578   Wolves       Bueno      DEF   4.0       0.0   0.0   0.0   0.000
579   Wolves        Neto      MID   6.4       0.0   0.0   0.0   0.000

[580 rows x 8 columns]

In [22]:
player_data.merge(team_data, left_on='Team', right_on='Team')

,Team,Player,Position,Cost,Selected,Form,Pts,ROI,Team_SPI,Team_attack_score,Team_defence_score,Opponent_SPI,Opponent_attack_score,Opponent_defence_score,Predicted_points,GF_likelihood,GA_likelihood
0,Arsenal,Ramsdale,GKP,5.1,16.7,4.0,70.0,13.725,77.9,2.1,0.6,68.60,1.8,0.775,6.70,1.325,0.333
1,Arsenal,Smith Rowe,MID,6.0,24.2,2.0,69.0,11.500,77.9,2.1,0.6,68.60,1.8,0.775,6.70,1.325,0.333
2,Arsenal,Gabriel,DEF,5.2,4.8,3.5,67.0,12.885,77.9,2.1,0.6,68.60,1.8,0.775,6.70,1.325,0.333
3,Arsenal,Saka,MID,6.2,8.8,3.0,58.0,9.355,77.9,2.1,0.6,68.60,1.8,0.775,6.70,1.325,0.333
4,Arsenal,Tomiyasu,DEF,4.7,5.3,3.3,54.0,11.489,77.9,2.1,0.6,68.60,1.8,0.775,6.70,1.325,0.333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,Wolves,Jonny,DEF,4.5,0.0,0.0,0.0,0.000,71.2,1.7,0.6,76.45,2.1,0.625,4.44,1.075,0.286
460,Wolves,Mosquera,DEF,4.5,0.0,0.0,0.0,0.000,71.2,1.7,0.6,76.45,2.1,0.625,4.44,1.075,0.286
461,Wolves,Marques,DEF,4.0,0.2,0.0,0.0,0.000,71.2,1.7,0.6,76.45,2.1,0.625,4.44,1.075,0.286
462,Wolves,Bueno,DEF,4.0,0.0,0.0,0.0,0.000,71.2,1.7,0.6,76.45,2.1,0.625,4.44,1.075,0.286
463,Wolves,Neto,MID,6.4,0.0,0.0,0.0,0.000,71.2,1.7,0.6,76.45,2.1,0.625,4.44,1.075,0.286

In [24]:
# get indepth player stats on prem_website - also selection rate